### ISSUE TITLE
QUESTION : support for bs 4 beta release

### ISSUE THREAD

**Issue by mattgi** [adamelliotfields/bootstrap-css-modules#1]
Are you looking to upgrade to the recent beta (and eventual stable) release of bootstrap.. just looking at the feasibility of taking a dependency on this lib. Ta.

**Comment by adamelliotfields** [comment]
Hi @mattgi ,

Totally planning on getting an update out in the next week - sorry it's been a bit overdue.

The version will be 4.3.0.

**Comment by adamelliotfields** [comment]
I'm going to leave this issue open until the new version goes live, but it is taking longer than I originally expected. There are quite a few changes - and not just to the CSS you use, but also to the mixins and variables that generate that CSS (there are new variables, existing variables have been renamed, and the function signatures of the mixins have changed). Once I'm done, there's going to be extensive changes to the documentation and most likely some sort of a migration guide.

In the meantime, here are some alternatives I've used:

### CSS Modules
 - [bootstrap-css](https://github.com/StevenIseki/bootstrap-css) is updated to 4.0.0-beta, but keep in mind it merely spits out individual CSS files for each of the source SCSS files. The class names are not camelCase and it doesn't take into account scoping (i.e., `.btn` from buttons.css is in a different scope than `.btn` from button-group.css). 
 - [react-css-modules](https://github.com/gajus/react-css-modules) can convert the class names to camelCase for you.

### React Components
 - [reactstrap](https://github.com/reactstrap/reactstrap) is also still on 4.0.0-alpha.6.
 - [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) is on 3.3.6.

### CSS-in-JS Libraries
 - Here is a [comparison](https://github.com/styled-components/comparison) from the styled-components library. I prefer using Radium, as it uses inline styles instead of generating class names at compile time like Aphrodite/Styled Components/Glamorous. With Radium, you can put your Bootstrap classes in the `className` attribute, and your custom styles in the `style` attribute. This also makes for a nicer debugging experience.

### Vanilla CSS
- Use [classnames](https://github.com/JedWatson/classnames) to conditionally add and remove classes.

**Comment by Meligy** [comment]
Hi,
Just leaving a note that Bootstrap 4 is now final ([announcement](http://blog.getbootstrap.com/2018/01/18/bootstrap-4/)).

**Comment by adamelliotfields** [comment]
Hey @Meligy, thanks for the update.

I'm going to update the README to show that this is unmaintained. There's a few forks - perhaps the authors of those are keeping them up to date.
